FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /build

COPY gym_admin\pom.xml .
COPY gym_admin/.mvn .mvn
COPY gym_admin/mvnw .
RUN chmod +x mvnw

COPY gym_admin/src ./src
RUN ./mvnw -B clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /build/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["sh","-c","java -jar /app/app.jar --server.port=${PORT:-8080}"]