# MongoDB Config
spring.mongodb.uri=${MONGODB_URL}
spring.mongodb.database=gymdb
spring.mongodb.auto-index-creation=true

# Cloudinary API
CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

JWT_SECRET_KEY=${JWT_SECRET_KEY}

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=plusegym@gmail.com
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.boot.context.config=TRACE